// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmHyHX_7dYKAh38AQMVeIdvdHpwYVQz_Y',
    appId: '1:261269582706:web:920614ddc78e646631e3eb',
    messagingSenderId: '261269582706',
    projectId: 'final123-b8d94',
    authDomain: 'final123-b8d94.firebaseapp.com',
    storageBucket: 'final123-b8d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX_aU84m_vSPq3M8NX1FvWEqceoDHAJ_I',
    appId: '1:261269582706:ios:3b7e82b7af08618131e3eb',
    messagingSenderId: '261269582706',
    projectId: 'final123-b8d94',
    storageBucket: 'final123-b8d94.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX_aU84m_vSPq3M8NX1FvWEqceoDHAJ_I',
    appId: '1:261269582706:ios:3b7e82b7af08618131e3eb',
    messagingSenderId: '261269582706',
    projectId: 'final123-b8d94',
    storageBucket: 'final123-b8d94.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmHyHX_7dYKAh38AQMVeIdvdHpwYVQz_Y',
    appId: '1:261269582706:web:184cc713a347e12531e3eb',
    messagingSenderId: '261269582706',
    projectId: 'final123-b8d94',
    authDomain: 'final123-b8d94.firebaseapp.com',
    storageBucket: 'final123-b8d94.appspot.com',
  );
}
